version: '3'
services:
        web:
                image: flask_barn_v1029
                build: .
                ports:
                        - "8923:8923"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
